# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetboss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetAccess',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fleet_access', models.BooleanField()),
                ('access', models.ManyToManyField(related_name='fleets_accessible', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleets_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
