# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetboss', '0002_fleetaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetaccess',
            name='fleet_access',
            field=models.BooleanField(default=False),
        ),
    ]
