# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetboss', '0003_auto_20160628_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetaccess',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='fleets_accessible', to=settings.AUTH_USER_MODEL),
        ),
    ]
