# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetboss', '0005_fleetaccess_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetaccess',
            name='link_join',
            field=models.BooleanField(default=False),
        ),
    ]
