categories = {
    'Abaddon': 'Battleship',
    'Absolution': 'Command Ship',
    'Aeon': 'Carrier',
    'Algos': 'Destroyer',
    'Anathema': 'Covert Ops',
    'Anshar': 'Jump Freighter',
    'Apocalypse': 'Battleship',
    'Apocalypse Imperial Issue': 'Battleship',
    'Apocalypse Navy Issue': 'Battleship',
    'Apotheosis': 'Shuttle',
    'Arazu': 'Recon Ship',
    'Arbitrator': 'Cruiser',
    'Archon': 'Carrier',
    'Ares': 'Interceptor',
    'Ark': 'Jump Freighter',
    'Armageddon': 'Battleship',
    'Ashimmu': 'Cruiser',
    'Astarte': 'Command Ship',
    'Astero': 'Frigate',
    'Atron': 'Frigate',
    'Augoror': 'Cruiser',
    'Augoror Navy Issue': 'Cruiser',
    'Avatar': 'Titan',
    'Badger': 'Industrial Ship',
    'Bantam': 'Frigate',
    'Basilisk': 'Logistics Cruiser',
    'Bellicose': 'Cruiser',
    'Bestower': 'Industrial Ship',
    'Bhaalgorn': 'Battleship',
    'Blackbird': 'Cruiser',
    'Breacher': 'Frigate',
    'Broadsword': 'Heavy Interdictor',
    'Brutix': 'Battlecruiser',
    'Burst': 'Frigate',
    'Bustard': 'Transport Ship',
    'Buzzard': 'Covert Ops',
    'Caldari Navy Hookbill': 'Frigate',
    'Capsule': 'Capsule',
    'Caracal': 'Cruiser',
    'Catalyst': 'Destroyer',
    'Celestis': 'Cruiser',
    'Cerberus': 'Heavy Assault Cruiser',
    'Chameleon': 'Recon Ship',
    'Cheetah': 'Covert Ops',
    'Chimera': 'Carrier',
    'Claw': 'Interceptor',
    'Claymore': 'Command Ship',
    'Coercer': 'Destroyer',
    'Condor': 'Frigate',
    'Confessor': 'Tactical Destroyer',
    'Corax': 'Destroyer',
    'Cormorant': 'Destroyer',
    'Covetor': 'Mining Barge',
    'Crane': 'Transport Ship',
    'Crow': 'Interceptor',
    'Crucifier': 'Frigate',
    'Cruor': 'Frigate',
    'Crusader': 'Interceptor',
    'Curse': 'Recon Ship',
    'Cyclone': 'Battlecruiser',
    'Cynabal': 'Cruiser',
    'Damnation': 'Command Ship',
    'Daredevil': 'Frigate',
    'Deimos': 'Heavy Assault Cruiser',
    'Devoter': 'Heavy Interdictor',
    'Dominix': 'Battleship',
    'Dragoon': 'Destroyer',
    'Drake': 'Battlecruiser',
    'Dramiel': 'Frigate',
    'Eagle': 'Heavy Assault Cruiser',
    'Enyo': 'Assault Frigate',
    'Eos': 'Command Ship',
    'Erebus': 'Titan',
    'Eris': 'Interdictor',
    'Executioner': 'Frigate',
    'Exequror': 'Cruiser',
    'Exequror Navy Issue': 'Cruiser',
    'Falcon': 'Recon Ship',
    'Federation Navy Comet': 'Frigate',
    'Ferox': 'Battlecruiser',
    'Flycatcher': 'Interdictor',
    'Garmur': 'Frigate',
    'Gila': 'Cruiser',
    'Gnosis': 'Battlecruiser',
    'Gold Magnate': 'Frigate',
    'Golem': 'Marauder',
    'Goru\'s Shuttle': 'Shuttle',
    'Griffin': 'Frigate',
    'Guardian': 'Logistics Cruiser',
    'Guardian-Vexor': 'Cruiser',
    'Guristas Shuttle': 'Shuttle',
    'Harbinger': 'Battlecruiser',
    'Harpy': 'Assault Frigate',
    'Hawk': 'Assault Frigate',
    'Hecate': 'Tactical Destroyer',
    'Hel': 'Carrier',
    'Helios': 'Covert Ops',
    'Heretic': 'Interdictor',
    'Heron': 'Frigate',
    'Hoarder': 'Industrial Ship',
    'Hound': 'Stealth Bomber',
    'Huginn': 'Recon Ship',
    'Hulk': 'Exhumer Barge',
    'Hurricane': 'Battlecruiser',
    'Hyena': 'Electronic Attack Frigate',
    'Hyperion': 'Battleship',
    'Ibis': 'Rookie Ship',
    'Imicus': 'Frigate',
    'Impairor': 'Rookie Ship',
    'Impel': 'Transport Ship',
    'Imperial Navy Slicer': 'Frigate',
    'Incursus': 'Frigate',
    'Inquisitor': 'Frigate',
    'Ishkur': 'Assault Frigate',
    'Ishtar': 'Heavy Assault Cruiser',
    'Iteron Mark V': 'Industrial Ship',
    'Jackdaw': 'Tactical Destroyer',
    'Jaguar': 'Assault Frigate',
    'Keres': 'Electronic Attack Frigate',
    'Kestrel': 'Frigate',
    'Kitsune': 'Electronic Attack Frigate',
    'Kronos': 'Marauder',
    'Kryos': 'Industrial Ship',
    'Lachesis': 'Recon Ship',
    'Legion': 'Strategic Cruiser',
    'Leviathan': 'Titan',
    'Loki': 'Strategic Cruiser',
    'Machariel': 'Battleship',
    'Mackinaw': 'Exhumer Barge',
    'Maelstrom': 'Battleship',
    'Magnate': 'Frigate',
    'Malediction': 'Interceptor',
    'Maller': 'Cruiser',
    'Mammoth': 'Industrial Ship',
    'Manticore': 'Stealth Bomber',
    'Mastodon': 'Transport Ship',
    'Maulus': 'Frigate',
    'Megathron': 'Battleship',
    'Megathron Federate Issue': 'Battleship',
    'Megathron Navy Issue': 'Battleship',
    'Merlin': 'Frigate',
    'Moa': 'Cruiser',
    'Moros': 'Dreadnought',
    'Muninn': 'Heavy Assault Cruiser',
    'Myrmidon': 'Battlecruiser',
    'Naga': 'Attack Battlecruiser',
    'Naglfar': 'Dreadnought',
    'Navitas': 'Frigate',
    'Nemesis': 'Stealth Bomber',
    'Nereus': 'Industrial Ship',
    'Nidhoggur': 'Carrier',
    'Nighthawk': 'Command Ship',
    'Nightmare': 'Battleship',
    'Noctis': 'Industrial Ship',
    'Nomad': 'Jump Freighter',
    'Nyx': 'Carrier',
    'Occator': 'Transport Ship',
    'Omen': 'Cruiser',
    'Omen Navy Issue': 'Cruiser',
    'Oneiros': 'Logistics Cruiser',
    'Onyx': 'Heavy Interdictor',
    'Oracle': 'Attack Battlecruiser',
    'Orca': 'Capital Industrial Ship',
    'Osprey': 'Cruiser',
    'Osprey Navy Issue': 'Cruiser',
    'Paladin': 'Marauder',
    'Panther': 'Black Op',
    'Phantasm': 'Cruiser',
    'Phobos': 'Heavy Interdictor',
    'Phoenix': 'Dreadnought',
    'Pilgrim': 'Recon Ship',
    'Probe': 'Frigate',
    'Procurer': 'Mining Barge',
    'Prophecy': 'Battlecruiser',
    'Prorator': 'Transport Ship',
    'Prospect': 'Exploration Frigate',
    'Proteus': 'Strategic Cruiser',
    'Prowler': 'Transport Ship',
    'Punisher': 'Frigate',
    'Purifier': 'Stealth Bomber',
    'Ragnarok': 'Titan',
    'Rapier': 'Recon Ship',
    'Raptor': 'Interceptor',
    'Rattlesnake': 'Battleship',
    'Raven': 'Battleship',
    'Raven Navy Issue': 'Battleship',
    'Raven State Issue': 'Battleship',
    'Reaper': 'Rookie Ship',
    'Redeemer': 'Black Op',
    'Republic Fleet Firetail': 'Frigate',
    'Retribution': 'Assault Frigate',
    'Retriever': 'Mining Barge',
    'Revelation': 'Dreadnought',
    'Rhea': 'Jump Freighter',
    'Rifter': 'Frigate',
    'Rokh': 'Battleship',
    'Rook': 'Recon Ship',
    'Rorqual': 'Capital Industrial Ship',
    'Rupture': 'Cruiser',
    'Sabre': 'Interdictor',
    'Sacrilege': 'Heavy Assault Cruiser',
    'Scimitar': 'Logistics Cruiser',
    'Scorpion': 'Battleship',
    'Scythe': 'Cruiser',
    'Scythe Fleet Issue': 'Cruiser',
    'Sentinel': 'Electronic Attack Frigate',
    'Sigil': 'Industrial Ship',
    'Silver Magnate': 'Frigate',
    'Sin': 'Black Op',
    'Skiff': 'Exhumer Barge',
    'Slasher': 'Frigate',
    'Sleipnir': 'Command Ship',
    'Stabber': 'Cruiser',
    'Stabber Fleet Issue': 'Cruiser',
    'Stiletto': 'Interceptor',
    'Stratios': 'Cruiser',
    'Succubus': 'Frigate',
    'Svipul': 'Tactical Destroyer',
    'Talos': 'Attack Battlecruiser',
    'Talwar': 'Destroyer',
    'Taranis': 'Interceptor',
    'Tempest': 'Battleship',
    'Tempest Fleet Issue': 'Battleship',
    'Tempest Tribal Issue': 'Battleship',
    'Tengu': 'Strategic Cruiser',
    'Thanatos': 'Carrier',
    'Thorax': 'Cruiser',
    'Thrasher': 'Destroyer',
    'Tormentor': 'Frigate',
    'Tornado': 'Attack Battlecruiser',
    'Tristan': 'Frigate',
    'Typhoon': 'Battleship',
    'Vagabond': 'Heavy Assault Cruiser',
    'Vargur': 'Marauder',
    'Velator': 'Rookie Ship',
    'Vengeance': 'Assault Frigate',
    'Vexor': 'Cruiser',
    'Vexor Navy Issue': 'Cruiser',
    'Viator': 'Transport Ship',
    'Vigil': 'Frigate',
    'Vigilant': 'Cruiser',
    'Vindicator': 'Battleship',
    'Vulture': 'Command Ship',
    'Widow': 'Black Op',
    'Wolf': 'Assault Frigate',
    'Worm': 'Frigate',
    'Wreathe': 'Industrial Ship',
    'Wyvern': 'Carrier',
    'Zealot': 'Heavy Assault Cruiser'
}

sizes = {
    'Assault Frigate': 'Frigate',
    'Attack Battlecruiser': 'Battlecruiser',
    'Battlecruiser': 'Battlecruiser',
    'Battleship': 'Battleship',
    'Black Op': 'Battleship',
    'Capital Industrial Ship': 'Capital',
    'Capsule': 'Capsule',
    'Carrier': 'Capital',
    'Command Ship': 'Battlecruiser',
    'Covert Ops': 'Frigate',
    'Cruiser': 'Cruiser',
    'Destroyer': 'Destroyer',
    'Dreadnought': 'Capital',
    'Electronic Attack Frigate': 'Frigate',
    'Exhumer Barge': 'Industrial Ship',
    'Exploration Frigate': 'Frigate',
    'Frigate': 'Frigate',
    'Heavy Assault Cruiser': 'Cruiser',
    'Heavy Interdictor': 'Cruiser',
    'Industrial Ship': 'Industrial Ship',
    'Interceptor': 'Frigate',
    'Interdictor': 'Destroyer',
    'Jump Freighter': 'Industrial Ship',
    'Logistics Cruiser': 'Cruiser',
    'Marauder': 'Battleship',
    'Mining Barge': 'Industrial Ship',
    'Recon Ship': 'Cruiser',
    'Rookie Ship': 'Rookie Ship',
    'Shuttle': 'Shuttle',
    'Stealth Bomber': 'Frigate',
    'Strategic Cruiser': 'Cruiser',
    'Tactical Destroyer': 'Destroyer',
    'Titan': 'Capital',
    'Transport Ship': 'Industrial Ship'
}
